-- Migration: Drop and Recreate donation table to match target DDL
-- Date: 2025-11-25
-- Migration ID: 015
-- Purpose: Complete table rebuild to match exact target DDL structure with IDENTITY column
-- Safety: Table is empty (0 rows), all dependent FKs properly handled

-- ==============================================================================
-- TRANSACTION START
-- ==============================================================================
BEGIN;

-- ==============================================================================
-- STEP 1: Drop all FKs referencing donation table
-- ==============================================================================
-- Three tables reference donation:
-- - donation_item (fk_donation_item_donation)
-- - dnintake (fk_dnintake_donation)
-- - donation_doc (fk_donation_doc_donation)

ALTER TABLE donation_item 
DROP CONSTRAINT IF EXISTS fk_donation_item_donation;

ALTER TABLE dnintake 
DROP CONSTRAINT IF EXISTS fk_dnintake_donation;

ALTER TABLE donation_doc 
DROP CONSTRAINT IF EXISTS fk_donation_doc_donation;

-- ==============================================================================
-- STEP 2: Drop the existing donation table
-- ==============================================================================
-- Table is empty (0 rows), so no data loss

DROP TABLE IF EXISTS donation CASCADE;

-- ==============================================================================
-- STEP 3: Create donation with target DDL structure
-- ==============================================================================
-- Uses GENERATED BY DEFAULT AS IDENTITY for donation_id

CREATE TABLE donation
(
    donation_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_donation PRIMARY KEY,

    donor_id INTEGER NOT NULL
        CONSTRAINT fk_donation_donor REFERENCES donor(donor_id),
    
    donation_desc TEXT NOT NULL,

    origin_country_id SMALLINT NOT NULL
        CONSTRAINT fk_donation_country REFERENCES country(country_id),
    
    origin_address1_text VARCHAR(255),
    origin_address2_text VARCHAR(255),

    event_id INTEGER NOT NULL
        CONSTRAINT fk_donation_event REFERENCES event(event_id),
    
    custodian_id INTEGER NOT NULL
        CONSTRAINT fk_donation_custodian REFERENCES custodian(custodian_id),

    received_date DATE NOT NULL
        CONSTRAINT c_donation_1 CHECK (received_date <= CURRENT_DATE),

    tot_item_cost DECIMAL(12,2) NOT NULL
        CONSTRAINT c_donation_2 CHECK (tot_item_cost >= 0.00),

    storage_cost DECIMAL(12,2) NOT NULL
        CONSTRAINT c_donation_2a CHECK (storage_cost >= 0.00),

    haulage_cost DECIMAL(12,2) NOT NULL
        CONSTRAINT c_donation_2b CHECK (haulage_cost >= 0.00),

    other_cost DECIMAL(12,2) NOT NULL
        CONSTRAINT c_donation_2c CHECK (other_cost >= 0.00),

    other_cost_desc VARCHAR(255),

    status_code CHAR(1) NOT NULL DEFAULT 'E'
        CONSTRAINT c_donation_3 CHECK (status_code IN ('E','V','P')),

    comments_text TEXT,

    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL DEFAULT 1
);

-- ==============================================================================
-- STEP 4: Re-add all FKs referencing donation
-- ==============================================================================

ALTER TABLE donation_item
ADD CONSTRAINT fk_donation_item_donation 
    FOREIGN KEY (donation_id) 
    REFERENCES donation(donation_id);

ALTER TABLE dnintake
ADD CONSTRAINT fk_dnintake_donation 
    FOREIGN KEY (donation_id) 
    REFERENCES donation(donation_id);

ALTER TABLE donation_doc
ADD CONSTRAINT fk_donation_doc_donation 
    FOREIGN KEY (donation_id) 
    REFERENCES donation(donation_id);

-- ==============================================================================
-- STEP 5: Add table comments for documentation
-- ==============================================================================

COMMENT ON TABLE donation IS 'Donations received from donors for disaster relief';
COMMENT ON COLUMN donation.donation_id IS 'Primary key - auto-generated identity';
COMMENT ON COLUMN donation.donor_id IS 'FK to donor who made the donation';
COMMENT ON COLUMN donation.donation_desc IS 'Description of the donation';
COMMENT ON COLUMN donation.origin_country_id IS 'Country of origin for the donation';
COMMENT ON COLUMN donation.event_id IS 'Event this donation is associated with (ADHOC for general)';
COMMENT ON COLUMN donation.custodian_id IS 'Agency that collected/holds the donation';
COMMENT ON COLUMN donation.received_date IS 'Date donation was received';
COMMENT ON COLUMN donation.tot_item_cost IS 'Total value of all items/funds donated';
COMMENT ON COLUMN donation.storage_cost IS 'Warehousing/storage costs';
COMMENT ON COLUMN donation.haulage_cost IS 'Transportation/shipping costs';
COMMENT ON COLUMN donation.other_cost IS 'Miscellaneous other costs';
COMMENT ON COLUMN donation.other_cost_desc IS 'Description of other costs';
COMMENT ON COLUMN donation.status_code IS 'E=Entered, V=Verified, P=Processed';

-- ==============================================================================
-- TRANSACTION COMMIT
-- ==============================================================================
COMMIT;

-- ==============================================================================
-- VERIFICATION QUERIES
-- ==============================================================================

-- Verify new table structure
SELECT 
    column_name,
    data_type,
    character_maximum_length,
    numeric_precision,
    numeric_scale,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'donation'
ORDER BY ordinal_position;

-- Display all constraints
SELECT 
    tc.constraint_name,
    tc.constraint_type
FROM information_schema.table_constraints AS tc
WHERE tc.table_name = 'donation'
ORDER BY tc.constraint_type, tc.constraint_name;

-- Verify all 3 FKs are restored
SELECT 
    tc.table_name AS referencing_table,
    tc.constraint_name,
    ccu.table_name AS references_table
FROM information_schema.table_constraints AS tc
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
    AND ccu.table_name = 'donation';

-- Verify identity column
SELECT 
    column_name,
    is_identity,
    identity_generation
FROM information_schema.columns
WHERE table_name = 'donation' AND column_name = 'donation_id';

-- ==============================================================================
-- MIGRATION COMPLETE
-- ==============================================================================
-- donation table recreated with:
-- ✓ IDENTITY column for donation_id (GENERATED BY DEFAULT AS IDENTITY)
-- ✓ All columns matching target DDL
-- ✓ All CHECK constraints: c_donation_1, 2, 2a, 2b, 2c, 3
-- ✓ All foreign keys: donor, country, event, custodian
-- ✓ All dependent FKs restored: donation_item, dnintake, donation_doc
-- ✓ Zero data loss (table was empty)
-- ==============================================================================
